apiVersion: v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
  - name: SUFFIX_NAME
    description: The suffix name for the template objects
    displayName: Suffix name
  - name: RELEASE_VERSION
    description: The release version number of application
    displayName: Release version
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: osio-angular${SUFFIX_NAME}
      labels:
        version: ${RELEASE_VERSION}
    spec: {}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: osio-angular-s2i${SUFFIX_NAME}
      labels:
          version: ${RELEASE_VERSION}
    spec:
      postCommit: {}
      resources: {}
      source:
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: DEV_MODE
              value: "true"
          from:
            kind: DockerImage
            name: 'bucharestgold/centos7-s2i-nodejs:10.x'
          incremental: true
      output:
        to:
          kind: ImageStreamTag
          name: 'osio-angular${SUFFIX_NAME}:${RELEASE_VERSION}'
      triggers: []
    status:
      lastVersion: 0
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      type: ClusterIP
      selector:
        project: osio-angular
        provider: nodeshift
    metadata:
      name: osio-angular${SUFFIX_NAME}
      labels:
        provider: nodeshift
        expose: 'true'
        project: osio-angular
        version: ${RELEASE_VERSION}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: osio-angular${SUFFIX_NAME}
      labels:
        app: osio-angular
        provider: nodeshift
        project: osio-angular
        version: ${RELEASE_VERSION}
    spec:
      template:
        spec:
          containers:
            - image: ""
              name: osio-angular
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
        metadata:
          labels:
            app: osio-angular
            project: osio-angular
            provider: nodeshift
            version: ${RELEASE_VERSION}
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: osio-angular
        project: osio-angular
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - osio-angular
            from:
              kind: ImageStreamTag
              name: "osio-angular${SUFFIX_NAME}:${RELEASE_VERSION}"
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        project: osio-angular
        provider: nodeshift
        version: ${RELEASE_VERSION}
      name: osio-angular${SUFFIX_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: osio-angular${SUFFIX_NAME}
